### PR TITLE
389

### PR DESCRIPTION
**Pull request by bunnygod**

### CODE REVIEW

**Review by mujingw — APPROVED** [review]
LGTM

**Comment by mujingw** [comment]
This is a map-reduce problem in functional programming. We `map` all the characters in `s` and `t` to their ASCII values and store them into a list, and then `reduce` the elements in this list by applying `^` to them.  

```python
def findTheDifference(self, s: str, t: str) -> str:
    def single_number(nums):
        return reduce(lambda x, y: x ^ y, nums)
    
    return chr(single_number([ord(ch) for ch in s + t]))

**Comment by bunnygod** [comment]
> ```python
> reduce
> ```

This is nuts, how did you learn it?

**Comment by mujingw** [comment]
> > ```python
> > reduce
> > ```
> 
> This is nuts, how did you learn it?

I don't know much about it. All I know is that it's a cool way to get the product or sum of _all elements_ in an array. In this particular problem, `^` has properties similar to those of addition and multiplication.

**Pull request merged**
