### PR TITLE
Check in 572.py.

### PR DESCRIPTION
**Pull request by bunnygod**

### CODE REVIEW

**Review by mujingw — APPROVED** [review]
LGTM. Can you figure out the time complexity of this algorithm?

**Comment by bunnygod** [comment]
> LGTM. Can you figure out the time complexity of this algorithm?

The time complexity is O(mn), m is the size of the tree and n is the size of the subtree.

**Comment by mujingw** [comment]
> > LGTM. Can you figure out the time complexity of this algorithm?
> 
> The time complexity is O(mn), m is the size of the tree and n is the size of the subtree.

Can you provide the reasoning that leads to this conclusion?

**Comment by bunnygod** [comment]
> > > LGTM. Can you figure out the time complexity of this algorithm?
> > 
> > 
> > The time complexity is O(mn), m is the size of the tree and n is the size of the subtree.
> 
> Can you provide the reasoning that leads to this conclusion?

Outer function isSubtree() needs to visit all nodes of the tree in worst case, while each visit we need to call isSameTree(). isSameTree() needs to visit all nodes of the subtree in the worst case.

**Comment by mujingw** [comment]
> > > > LGTM. Can you figure out the time complexity of this algorithm?
> > > 
> > > 
> > > The time complexity is O(mn), m is the size of the tree and n is the size of the subtree.
> > 
> > 
> > Can you provide the reasoning that leads to this conclusion?
> 
> Outer function isSubtree() needs to visit all nodes of the tree in worst case, while each visit we need to call isSameTree(). isSameTree() needs to visit all nodes of the subtree in the worst case.

LGTM. Makes sense.

**Pull request merged**
